### ISSUE TITLE
Question: Windows support

### ISSUE THREAD

**Issue by AmiZya** [sminez/ad#28]
Hello sminez,

Thank you for the great editor I watched your intro video and it looks pretty interesting I wanted to test it.

But it doesn't compile well on Windows, is this platform even supported currently? If so how to proceed?

Thanks!

**Comment by sminez** [comment]
Thanks for taking an interest in ad! I'm afraid the core of the editor relies around using unix domain sockets for serving the file system interface which isn't currently supported in the standard library (though judging from [this issue](https://github.com/rust-lang/libs-team/issues/271#issuecomment-2356675754) it looks like it's now being worked on?)

I suspect the compile errors are around clipboard support which is currently only implemented for linux and osx [here](https://github.com/sminez/ad/blob/develop/src/util.rs#L15-L48). If you have an idea of what that should look like then I'm open to accepting a PR that adds equivalent code for windows but importantly, I also don't have a windows machine to build or test the project on. So ensuring that everything stayed functional as I work on that side of the codebase isn't something I can currently commit to I'm afraid. As and when the project reaches a stable state it might be possible for me to take on windows support but I'll have to look at how much time I can dedicate to it when I hit that point.
