### ISSUE TITLE
Execute a command using selected text

### ISSUE THREAD

**Issue by davcam** [sminez/ad#31]
Great project @sminez. 

Here I'm trying to recreate functionality in acme  which I use to send selected code to a running REPL using acme's win shell. 
For ad I have created a script "mysend" (see below) which uses tmux instead but the principle is the same.  

The issue is that I want to send the code I've selected not the text "mysend" to the REPL

### Is this a feature you have seen in other text editors?

In acme it is possible to select text and then middle click on a "command" (which could for example be a shell script such as mysend) without the selected text "dot" changing to command name. 

### Please describe the change / addition you'd like to see made

The idea is to select text and then click on a command "mysend" to send the text to a REPL

mysend is a bash script which sends the selected text to a tmux pane (pane 0) which could be running bash/python/R or whatever REPL

```
#!/bin/bash

source "$HOME/.ad/lib/ad.sh"

# read selected text from ad into a variable
varin="$(bufRead "$bufid" dot)"

# split up each line by reading into an array
readarray -t cmdarray <<< $varin

# send each line of the array to tmux
for i in "${cmdarray[@]}"
do
        tmux send -t%0 $i Enter
done

```

The issue at the moment is that when I click on mysend it changes dot from the selected text to "mysend" so that the REPL executes "mysend" rather than the code selected.

**Comment by sminez** [comment]
Hi @davcam, thank you for taking an interest in `ad`! This is something I've been wondering about as well actually, I started trying to write a version of `win` that would be runnable inside of `ad` but ended up getting distracted by other things.

I've been meaning to look a bit more at mouse selection as part of https://github.com/sminez/ad/issues/8 and was thinking about adding the acme behaviour you are describing of supporting dragging the middle or right mouse buttons to make a second (differently highlighted) selection for executing and loading the current dot. I'm not sure how long that will take to implement (hopefully not too long) but I'll try to take a look over the next week or so if I have time. For now though, I think that the approach you've got here could work "as is" if you added a key-binding to your [init.conf](https://github.com/sminez/ad/blob/develop/data/init.conf#L46) that ran `mysend`, but that obviously isn't exactly the same set up as is possible in acme.

**Comment by davcam** [comment]
Many thanks for your reply @sminez. ad seems to hit a sweet spot, at least for me and hopefully for quite a number of others.  

An ad version of win would be great of course though I guess more work?

Yes a differently highlighted dot using the middle mouse selection for executing is the feature I'm keen to see from acme. 

In the meantime thanks for pointing me towards init.conf

**Comment by sminez** [comment]
OK, not exactly the same setup as what you have above but I can get the following to work:
```bash
#!/bin/bash
source "$HOME/.ad/lib/ad.sh"

requireAd

# read selected text from ad into a variable
varin="$(bufRead "$bufid" dot)"
tmux send -t%21 "$varin" Enter
```

Here, `21` is the pane ID for the pane I had open but I'm not too sure how you would determine that dynamically. In the recording after I highlight the line I'm just hitting `S` to trigger the key-binding shown in `init.conf`.

I'll keep this issue open until I have the acme style functionality implemented :slightly_smiling_face: 

https://github.com/user-attachments/assets/485009d0-7355-4d89-805c-9b15cbee78d7

**Comment by sminez** [comment]
> An ad version of win would be great of course though I guess more work?

I had a look at the `win` source code and it does a fair amount of book keeping to filter out re-interpreting its own input as it gets fed into the window after running each command. I _think_ I have an idea of how to handle that but I'll need to get an MVP up and running to be able to verify that what I have planned will work. I should probably raise an issue for that as well so people are able to see what sorts of things I have planned for the future :smile:

**Comment by davcam** [comment]
Yep exactly and nice demo too!

**Comment by sminez** [comment]
@davcam I've got a PR open now that adds acme style mouse chording and Load / Execute selections while maintaining the current dot selection. As I've said in the PR description, I'm not asking for a code review as that'd be a bit much(!) but please do take a look at the demo and see what you think :smile: 

I'm working on adding some unit tests for the new functionality before merging. It's a little fiddly given the interactions with the clipboard so I've got some refactoring to do but the current state of the PR should accurately reflect how things are going to work.

**Comment by sminez** [comment]
Now implemented as of #35

**Comment by davcam** [comment]
@sminez sorry to have taken my time getting back to you on this. 

First of all thanks very much for this really useful set of changes to the mouse behaviour. This makes the ad editor even more compelling than before.  

BTW I am now essentially using the workflow that you suggested before by defining a key press to run the mysend script. 

I think your point below from the PR should address my original enhancement query? 
Middle (click+release): Execute Dot (expanding current dot from Cur if needed)

However when I tested it I didn't get the result I expected. 

Below is an example using your "Send" script from above 

If I highlight echo hello then middle click on Send. The shell reports "Send: command not found" because in clicking the middle mouse button it has changed dot from "echo hello" to "Send" whereas I was expected it to use the current dot "echo hello" to send to the other tmux pane. 

echo hello
Send  

So I guess strictly my original issue still stands and is perhaps now a bug?  

Although just to repeat I do not need this workflow now and your mouse behaviour changes are great.

**Comment by sminez** [comment]
Hi @davcam :wave:

No worries about taking your time to reply, there's no rush! I've just tried out the `Send` script again with the new functionality and it works fine for me but there might be one part that isn't working as you expect / how acme handled things. This is what works for me

- use the left mouse button to drag highlight `echo hello`
- use the middle mouse button to drag highlight `Send`

What doesn't work is just clicking the middle button on `Send`. Is that what you were trying?

**Comment by davcam** [comment]
Thanks for your reply @sminez 

"What doesn't work is just clicking the middle button on Send. Is that what you were trying?"
Yes exactly this. This would be quite useful as it avoids the need to highlight the command "Send" but isn't a major point. 

"use the left mouse button to drag highlight echo hello"
"use the middle mouse button to drag highlight Send"

If I understand correctly, this uses dot as an argument to Send so essentially Send echo hello? This is fine if the script expects to receive arguments $*. This is like a 2-1 mouse chord in acme I think?

In my case the script expects to read dot using 9p ie varin="$(bufRead "$bufid" dot)". An easy change to my script would fix this.  

As you state ad isn't meant to be a carbon copy of acme.
