### ISSUE TITLE
Question: Shell pipe also copies to system clipboard

### ISSUE THREAD

**Issue by izuzak** [sminez/ad#33]
Hello! 👋 

**Praise:** Love the ideas, love the editor, would love to learn more about it and use it more! Well done 👏 

**Question:** when piping selected text to an external program, the selected text is also copied to the system clipboard. Wanted to ask if that's intentional, understand a bit more why, and whether it'd make sense to provide a way to pipe without copying to the clipboard? 💭 When I do the same thing in `vim`, the contents is not copied to the clipboard, and that's more in line with my expectations. But I'm open to learning about why `ad` does it differently and potentially adjusting my expectations. 😄  

Here's a GIF:

![Screenshot 2024-10-11 at 09 05 08](https://github.com/user-attachments/assets/3ec01c58-a12b-4a3e-9878-6a37410bbf21)

I found [this](https://github.com/sminez/ad/blob/7506b582b41304e0812aad24f3417ddfce419e57/src/editor/actions.rs#L360-L366) and [this](https://github.com/sminez/ad/blob/fcfd2b75bd9b69da0665fbaedeedbacf874f2901/src/editor/actions.rs#L689) in the source code, and I think they connect [here](https://github.com/sminez/ad/blob/7506b582b41304e0812aad24f3417ddfce419e57/src/buffer/mod.rs#L891-L896). Is that right? 

Thanks again! 🙇

**Comment by srenatus** [comment]
(Just a fellow ad user here.)

I checked what ends up in the clipboard, and it's the _previous selection_. So it behaves consistently with, say, `d` to delete the selection: what was selected previously is yanked (into the system clipboard because that's the only clipboard ad has, I suppose?).

**Comment by sminez** [comment]
Hi @izuzak :wave: Thank you very much for the kind words!

It's still reasonably early days for the project in terms of it being actually usable for day-to-day tasks so I suspect there are likely going to be several behaviour changes over the coming months as more people test it out and let me know where things do / don't make sense.

In this case @srenatus is correct both in terms of the observed behaviour and the intended behaviour: all `delete` actions within `ad` will set the content of the system clipboard. This applies to explicit delete of ranges (not single characters) and inserts while the current selection is a range which is what you are seeing here. `ad` does not maintain any internal clipboards or buffers in the way that vim does and I want (as far as possible) for actions that manipulate the buffer state to be as self-consistent as possible. That said, I could see the argument for _not_ setting the clipboard state in this way when you are replacing the current selection. One particular case I can see where this would be annoying is if you wanted to repeatedly paste something into the buffer as a replacement for other regions of text, as you'd end up pasting pack the text you just removed. And now that I think about it, I'm not setting the clipboard in a consistent way if you use `Edit` commands either, as you'll end up with the contents being the final selection that was deleted (if any) which probably isn't overly useful(!)

So overall, I think it's probably best to update the handling you've linked to [here](https://github.com/sminez/ad/blob/7506b582b41304e0812aad24f3417ddfce419e57/src/buffer/mod.rs#L891-L896) to simply remove the current selection and not pass it back for insertion into the system clipboard.

**Comment by izuzak** [comment]
I forgot to say thank you for the detailed explanation and for the quick change -- many thanks! 🙇
