### ISSUE TITLE
Acme like mouse click selections

### ISSUE THREAD

**Issue by Superpat** [sminez/ad#41]
### Please describe the change / addition you'd like to see made

- Is this completely new functionality, or an enhancement to existing functionality?
Unclear to me if this can already be supported by existing functionality. 

- What kind of feature is it that you are requesting?
I want double clicking to contextually select text.
  -  on a word to select the whole word
  -  at the beginning or ending of a line to select the whole line
  - before or after a block delimiter to select the whole block, examples include parens, curly brackets, brackets and quotes. Though there might be a way to make this even better with LSP or treesitter.

### Is this a feature you have seen in other text editors?
Acme, though double clicking to select a word is pretty common. Triple clicking to select a line is also common, but not present in acme, though it could work well.

If so, please provide any links or reference to the existing implementation
and some details on how the feature is used.
I use this extensively, it's often quicker to copy paste this way then it is to use Edit.

**Comment by sminez** [comment]
This was implemented here: https://github.com/sminez/ad/issues/38#issuecomment-2414842446

Unless I'm misunderstanding what you are asking for?

**Comment by Superpat** [comment]
Yeah that stuff works, I'm talking about left mouse click double click. But acme also selects the whole word / line / block you're clicking on when you double click.

**Comment by sminez** [comment]
That's what is happening in the video I linked to 🙂

Double click selection of lines and delimited pairs works as you are describing here, other than "on a word to select the whole word": if you double click at the start of a word it will select until the next space character.

**Comment by Superpat** [comment]
Oh my bad, somehow last time I clicked on that link I got brought somewhere else and didnt see that video and that commit isnt in the latest release yet so just doing cargo install wasnt getting it. Thanks.
