### ISSUE TITLE
OpenBSD support

### ISSUE THREAD

**Issue by Superpat** [sminez/ad#42]
I'd like to see OpenBSD support.

 I tried compiling on OpenBSD-current, but it would not compile correctly. I'm open to trying to fix this myself, but I'll need guidance on the rust front. 

Also this might be a simple fix, so I'm asking you first.

```
   Compiling tracing v0.1.40=======>     ] 27/32: ad_event, tracing-attributes
error[E0277]: the trait bound `DefaultSystem: system::System` is not satisfied
  --> src/editor/mod.rs:94:6
   |
94 | impl Editor<DefaultSystem> {
   |      ^^^^^^^^^^^^^^^^^^^^^ the trait `system::System` is not implemented for `DefaultSystem`
   |
help: this trait has no implementations, consider adding one
  --> src/system.rs:16:1
   |
16 | pub trait System: fmt::Debug {
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
note: required by a bound in `Editor`
  --> src/editor/mod.rs:58:8
   |
56 | pub struct Editor<S>
   |            ------ required by a bound in this struct
57 | where
58 |     S: System,
   |        ^^^^^^ required by this bound in `Editor`

error[E0277]: the trait bound `DefaultSystem: system::System` is not satisfied
   --> src/editor/mod.rs:101:10
    |
101 |     ) -> Self {
    |          ^^^^ the trait `system::System` is not implemented for `DefaultSystem`
    |
help: this trait has no implementations, consider adding one
   --> src/system.rs:16:1
    |
16  | pub trait System: fmt::Debug {
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
note: required by a bound in `Editor`
   --> src/editor/mod.rs:58:8
    |
56  | pub struct Editor<S>
    |            ------ required by a bound in this struct
57  | where
58  |     S: System,
    |        ^^^^^^ required by this bound in `Editor`

error[E0599]: the function or associated item `new_with_system` exists for struct `Editor<DefaultSystem>`, but its trait bounds were not satisfied
   --> src/editor/mod.rs:102:15
    |
56  | pub struct Editor<S>
    | -------------------- function or associated item `new_with_system` not found for this struct
...
102 |         Self::new_with_system(cfg, plumbing_rules, mode, log_buffer, De...
    |               ^^^^^^^^^^^^^^^ function or associated item cannot be called on `Editor<DefaultSystem>` due to unsatisfied trait bounds
    |
   ::: src/system.rs:67:1
    |
67  | pub struct DefaultSystem;
    | ------------------------ doesn't satisfy `DefaultSystem: system::System`
    |
note: if you're trying to build a new `Editor<DefaultSystem>`, consider using `Editor::<DefaultSystem>::new` which returns `Editor<DefaultSystem>`
   --> src/editor/mod.rs:96:5
    |
96  | /     pub fn new(
97  | |         cfg: Config,
98  | |         plumbing_rules: PlumbingRules,
99  | |         mode: EditorMode,
100 | |         log_buffer: LogBuffer,
101 | |     ) -> Self {
    | |_____________^
note: trait bound `DefaultSystem: system::System` was not satisfied
   --> src/editor/mod.rs:108:8
    |
106 | impl<S> Editor<S>
    |         ---------
107 | where
108 |     S: System,
    |        ^^^^^^ unsatisfied trait bound introduced here
note: the trait `system::System` must be implemented
   --> src/system.rs:16:1
    |
16  | pub trait System: fmt::Debug {
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
error[E0277]: the trait bound `DefaultSystem: system::System` is not satisfied
   --> src/editor/mod.rs:102:9
    |
102 |         Self::new_with_system(cfg, plumbing_rules, mode, log_buffer, De...
    |         ^^^^ the trait `system::System` is not implemented for `DefaultSystem`
    |
help: this trait has no implementations, consider adding one
   --> src/system.rs:16:1
    |
16  | pub trait System: fmt::Debug {
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
note: required by a bound in `Editor`
   --> src/editor/mod.rs:58:8
    |
56  | pub struct Editor<S>
    |            ------ required by a bound in this struct
57  | where
58  |     S: System,
    |        ^^^^^^ required by this bound in `Editor`

Some errors have detailed explanations: E0277, E0599.
For more information about an error, try `rustc --explain E0277`.
error: could not compile `ad-editor` (lib) due to 4 previous errors

```

**Comment by Superpat** [comment]
By copying the linux block in src/system.rc and renaming it openbsd, I can compile and use successfully. 

The only thing that doesnt seem to be working is the double click selection expansion and I just tested that it worked on my void linux laptop.

**Comment by Superpat** [comment]
`xclip -selection clipboard -o` works on OpenBSD so I dont think it's related to that.

**Comment by Superpat** [comment]
I think this is specific to the OpenBSD xterm. I downloaded a different terminal (alacritty) and the double click expansion works fine there.

**Comment by sminez** [comment]
I was going to say that I need to find a way of interacting with the clipboard that doesn't involve using a subprocess call to things like xclip but then I found this:
 https://github.com/neovim/neovim/blob/f2906a4669a2eef6d7bf86a29648793d63c98949/runtime/autoload/provider/clipboard.vim#L68-L152

Which is then used as a reference for how helix does it as well, so I suspect this approach is actually reasonably standard? 😅

With that in mind though, what I should do is determine (at start up) what the clipboard provider needs to be rather than hard coding things based on the OS, which already won't work for Wayland I suspect. I currently have a pretty big PR in flight that is overhauling the UI which I'd like to land first before taking a look at this, but I'll hopefully get it sorted after that.

As for BSD support in general, that's going to have to be a best effort "if it works it works" deal I'm afraid as I don't have a BSD set up to test things on. As the readme points out, the project is still very young and there are likely to be a number of bugs and behaviour changes in the short to midterm, so please do keep that in mind 🙂

**Comment by Superpat** [comment]
Well I'll be playing with this on OpenBSD for the time being so if I see anything that's within my capacity to handle I'll send pull requests. I fully understand the status of the project.

**Comment by sminez** [comment]
That's kind of you to offer but my point is more that as and when things break on platforms other than Linux during this stage of the project I won't be guaranteeing support for those platforms. Like I said, I have no way of verifying BSD specific changes myself so I won't be able to review or merge PRs of that nature.

Once the project is more mature and there is less churn in the internals of the code base I should be able to sort out which platforms are supported (and how I will support them). Ideally there shouldn't be any OS specific logic in `ad` that would cause problems like this but that's not something I can say one way or the other at the moment.
