### ISSUE TITLE
status line: theme color stops a bit too early

### ISSUE THREAD

**Issue by srenatus** [sminez/ad#45]
When I save, the theme color stops a bit too early in the status line:

<img width="1255" alt="image" src="https://github.com/user-attachments/assets/869007ff-56e5-46d7-88ae-a06d5b356b8f">
<img width="1249" alt="Screenshot 2024-10-28 at 11 13 06" src="https://github.com/user-attachments/assets/954746af-3f60-4a20-8ff5-cb3bf38a2cb7">

when the messages goes away, it's again colored as expected:

<img width="1251" alt="image" src="https://github.com/user-attachments/assets/d31e8bd6-4a75-494c-9eec-0ed7dbbdb980">

_Originally posted by @srenatus in https://github.com/sminez/ad/issues/44#issuecomment-2441153721_

**Comment by srenatus** [comment]
I've been a bit lazy here copying this from #44. If you need any more information, I'm happy to provide it! :)

**Comment by sminez** [comment]
This was just a case of me setting the background colour at the wrong point when rendering the message bar it seems. I also noticed that the colours can end up incorrect when you are typing at the command prompt which is also fixed by the commit above.

**Comment by srenatus** [comment]
Thanks for the quick fix! 😃
