### ISSUE TITLE
Buffer confusion after :dc

### ISSUE THREAD

**Issue by leahneukirchen** [sminez/ad#52]
### Describe the bug

When a column is deleted, the other column is shown but ad thinks the deleted buffer is still active.

### To Reproduce

```
% ad README.md
:O LICENSE
:dc
```

Now ad shows `LICENSE - 19 lines`, but still displays README.md.  The cursor can't be moved more than 19 lines.

### Expected behavior

:dc deletes the column and displays the other buffer

### Versions & OS Details

- OS: Linux
- Distribution Void
- ad Version: d2494246f73e255da387c98d9183021907f136be

**Comment by sminez** [comment]
hi @leahneukirchen, thank you for raising this! It looks like it also affected closing windows as well and the fix is the same in both cases. The latest commit on `main` now correctly focuses the active buffer internally.
